### ISSUE TITLE
List operators that don't use OLM

### ISSUE THREAD

**Issue by mattfarina** [operator-framework/operatorhub.io#255]
> An Operator is an application-specific controller that extends the Kubernetes API to create, configure, and manage instances of complex stateful applications on behalf of a Kubernetes user. It builds upon the basic Kubernetes resource and controller concepts but includes domain or application-specific knowledge to automate common tasks.

From the [introduction of operators](https://coreos.com/blog/introducing-operators.html) (quote above taken from there), operators have had a lot of great potential.

What has not been part of being an operator is the way it is installed/updated/etc. The current OperatorHub implementation requires of the use of OLM. But, operators can be installed and have their lifecycles managed with varying different tools. In it's simplest form, raw Kubernetes manifests and kubectl could be used. This idea could be used with a GitOps workflow, too.

Since this is OperatorHub, and not OLMHub, can it be made so that all operators can be listed no matter the mechanism used to install them.

**Comment by dmesser** [comment]
OperatorHub does not require the use of OLM but the use of the packaging format. Since this site also provides a starting point for installation which shows the steps done with OLM, I can understand the impression you have.

I think it is a fair request to make it easier to list Operators in other packaging formats, e.g. helm. The best approach would be to settle on a common metadata format for Operators that is independent of the packaging that enables the lifecycle. We could start this discussion in CNCF sig-app-delivery, as there are also specifications that exist already and might present a good starting point.

One feature, that people find useful, is that submissions to OperatorHub.io are actually tested before they land on the site and as a result can provide install instructions on the site that work right away.
So in my opinion the supported packaging formats should allow for that. `kubectl apply -f` would also work if we can codify it so it can be done with a single call in the admission pipeline. The thing we would probably like to avoid is no install instructions at all and the site lists content that does not really work.

**Comment by mattfarina** [comment]
> One feature, that people find useful, is that submissions to OperatorHub.io are actually tested before they land on the site and as a result can provide install instructions on the site that work right away.

I like this too. The Helm project has long tested every change to land in the stable and incubator repositories. The chart maintainers have developed tools for others to test their own charts and repositories.

I would imagine that for Kubernetes manifests and for Helm charts it would be possible to develop testing mechanisms.

> The thing we would probably like to avoid is no install instructions at all and the site lists content that does not really work.

Agreed. The experience to install should be simple and easy to discover.

> The best approach would be to settle on a common metadata format for Operators that is independent of the packaging that enables the lifecycle. We could start this discussion in CNCF sig-app-delivery, as there are also specifications that exist already and might present a good starting point.

This sounds fine to me. Do you have an existing specifications in mind? Documenting here would let myself and others start to read them.

**Comment by Lawouach** [comment]
Hi all,

Just a mere operator developer here, I'm not sure what this means to folks creating operator that aren't in Go (thus not using the Operator framework) nor packages as Helm (I'm using Kustomize and straight manifests). I wonder if that means I'm out of the loop for OperatorHub in this case? If so, is there room for me to change something based on the discussion here?

Thank you,

**Comment by dmesser** [comment]
@Lawouach This is the reason why we would discuss a common metadata format so a submission like your could even be displayed in the catalog. Ideally you'd add this metadata to your kustomize overlays and manifests and get an entry to appear. Then we'd would also need to have a way to codify `kustomize` based submissions so there is a way to display install instructions like we do now.

**Comment by Lawouach** [comment]
Neat. That's good to hear non-helm users are indeed not forgotten :)

**Comment by mattfarina** [comment]
@dmesser Is the metadata you need documented somewhere?

**Comment by dmesser** [comment]
@njhale This discussion is probably a good start to gather/present the list of catalog-only metadata from the CSV we spoke about last time.

**Comment by dmesser** [comment]
@mattfarina The metadata section of the CSV today is described here: https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata

I like us to work together on defining a common denominator of this kind of data so we could just depend on certain fields to be in the CSV and `Chart.yaml` which drive the visual display on OperatorHub.io. 

PS: There is also KEP open to talk about how to ship this data around and we'd like your input as well. It could easily have a `mediatype` for Helm.

**Comment by Lawouach** [comment]
Hi @dmesser How do you want to progress for non-Helm users then? Since there is no Chart.yaml file that is.

**Comment by dmesser** [comment]
@Lawouach I think we want to identify the common denominator in metadata first and than supply that via different means, i.e. in `Chart.yaml` for helm-packaged Operators, `CSV` for OLM-packaged Operators and an additional YAML structure for `kustomize`. Do you have proposals?

**Comment by Lawouach** [comment]
Makes sense and I don't have one yet. I'll be thinking about it.

Cheers!

**Comment by robszumski** [comment]
Supporting different packaging formats has been an ongoing exploration and I wanted to share a POC of viewing a Helm chart packaged Operator in OperatorHub.io. Below you can see the Jetstack certificate Operator viewable on the dev site:

https://dev.operatorhub.io/operator/cert-manager

A few things to note about this:
 - Existing cert-manager Operator packaged as Helm chart from the stable chart repo
 - Renders the chart description, chart version and more in a consistent format with the rest of the site
 - Install instructions point towards `helm install` instead of OLM commands
 - This Operator allows for the Day 2 experience that admins and developers love about Operators as new Ingress endpoints are added and removed
 - OLM wasn’t used to create this and is not required to run this

This is just a quick POC to show how these could work on OperatorHub and as we’ve been saying for months, we are open to collaboration around this issue. Right now the POC is based on a hand-crafted package definition taken from the helm chart. This would be automated in the future so contributors can simply send pointers to the helm repo. This means there is some more work to do of course and I don’t expect to see the implementation merged into the live site in the current form, but it’s directionally correct.
